In [1]:
import pandas as pd
import requests
import json
from pprint import pprint
from sqlalchemy import create_engine

In [2]:
#data from CSV file exported from FanGraphs
csv_file = "yankees.csv"
yankees_df = pd.read_csv(csv_file)
yankees_df.head()

,Name,G,PA,HR,R,RBI,SB,BB%,K%,ISO,...,AVG,OBP,SLG,wOBA,wRC+,BsR,Off,Def,WAR,playerid
0,DJ LeMahieu,145,655,26,109,102,5,7.0 %,13.7 %,0.191,...,0.327,0.375,0.518,0.375,136.0,-0.8,29.2,2.8,5.4,9874
1,Aaron Judge,102,447,27,75,55,3,14.3 %,31.5 %,0.267,...,0.272,0.381,0.540,0.382,141.0,0.4,23.7,7.6,4.6,15640
2,Gleyber Torres,144,604,38,96,90,5,7.9 %,21.4 %,0.256,...,0.278,0.337,0.535,0.358,125.0,-0.5,18.7,-2.6,3.6,16997
3,Brett Gardner,141,550,28,86,74,10,9.5 %,19.6 %,0.253,...,0.251,0.325,0.503,0.344,115.0,4.6,15.2,2.5,3.6,9927
4,Giovanny Urshela,132,476,21,73,74,1,5.3 %,18.3 %,0.219,...,0.314,0.355,0.534,0.369,132.0,-3.1,16.4,-1.1,3.1,10681

In [3]:
#Cleaning up for the columns we want
nyy_df = yankees_df[['Name', 'HR', 'AVG', 'OBP', 'RBI', 'SB']].copy()
nyy_df['Name'][4] = 'Gio Urshela'
nyy_df

C:\Users\Micha\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

                 Name  HR    AVG    OBP  RBI  SB
0         DJ LeMahieu  26  0.327  0.375  102   5
1         Aaron Judge  27  0.272  0.381   55   3
2      Gleyber Torres  38  0.278  0.337   90   5
3       Brett Gardner  28  0.251  0.325   74  10
4         Gio Urshela  21  0.314  0.355   74   1
5       Mike Tauchman  13  0.277  0.361   47   6
6        Gary Sanchez  34  0.232  0.316   77   0
7           Luke Voit  21  0.263  0.378   62   0
8      Cameron Maybin  11  0.285  0.364   32   9
9         Aaron Hicks  12  0.235  0.325   36   1
10     Didi Gregorius  16  0.238  0.276   61   2
11      Austin Romine   8  0.281  0.310   35   1
12  Edwin Encarnacion  13  0.249  0.325   37   0
13          Mike Ford  12  0.259  0.350   25   0
14    Kyle Higashioka   3  0.214  0.211   11   0
15  Giancarlo Stanton   3  0.288  0.403   13   0
16         Tyler Wade   2  0.245  0.330   11   7
17     Thairo Estrada   3  0.250  0.294   12   4
18      Clint Frazier  12  0.267  0.317   38   1
19     Breyvic Valera   0  0.219  0.324    3   0
20    Troy Tulowitzki   1  0.182  0.308    1   0
21      Adam Ottavino   0  0.000  0.000    0   0
22       Zack Britton   0  0.000  0.000    0   0
23    Dellin Betances   0  0.000  0.000    0   0
24       Cory Gearrin   0  0.000  0.000    0   0
25         David Hale   0  0.000  0.000    0   0
26    Aroldis Chapman   0  0.000  0.000    0   0
27        Tyler Lyons   0  0.000  0.000    0   0
28       Tommy Kahnle   0  0.000  0.000    0   0
29       Jake Barrett   0  0.000  0.000    0   0
30          Ryan Dull   0  0.000  0.000    0   0
31         Brady Lail   0  0.000  0.000    0   0
32       Joe Mantiply   0  0.000  0.000    0   0
33         Ben Heller   0  0.000  0.000    0   0
34    Stephen Tarpley   0  0.000  0.000    0   0
35      Luis Severino   0  0.000  0.000    0   0
36         Joe Harvey   0  0.000  0.000    0   0
37  Jordan Montgomery   0  0.000  0.000    0   0
38    Jonathan Holder   0  0.000  0.000    0   0
39      Nestor Cortes   0  0.000  0.000    0   0
40        Adonis Rosa   0  0.000  0.000    0   0
41       Chance Adams   0  0.000  0.000    0   0
42  Jonathan Loaisiga   0  0.000  0.000    0   0
43       Michael King   0  0.000  0.000    0   0
44         Luis Cessa   0  0.000  0.000    0   0
45         Chad Green   0  0.000  0.000    0   0
46    Masahiro Tanaka   0  0.000  0.000    0   0
47        CC Sabathia   0  0.000  0.000    0   0
48          J.A. Happ   0  0.000  0.000    0   0
49          Greg Bird   1  0.171  0.293    1   0
50       James Paxton   0  0.000  0.000    1   0
51     Domingo German   0  0.000  0.000    0   0
52    Kendrys Morales   1  0.177  0.320    5   0
53     Miguel Andujar   0  0.128  0.143    1   0

In [4]:
#testing the response to see what the JSON looks like
url= "http://lookup-service-prod.mlb.com/json/named.search_player_all.bam?sport_code='mlb'&active_sw='Y'&name_part="
response = requests.get(url + "'"+nyy_df['Name'][0]+"'")
print(response.url)

http://lookup-service-prod.mlb.com/json/named.search_player_all.bam?sport_code='mlb'&active_sw='Y'&name_part='DJ%20LeMahieu'

In [5]:
data = response.json()
pprint(data)

{'search_player_all': {'copyRight': ' Copyright 2019 MLB Advanced Media, L.P.  '
                                    'Use of any content on this page '
                                    'acknowledges agreement to the terms '
                                    'posted here '
                                    'http://gdx.mlb.com/components/copyright.txt  ',
                       'queryResults': {'created': '2019-10-12T15:01:27',
                                        'row': {'active_sw': 'Y',
                                                'bats': 'R',
                                                'birth_city': 'Visalia',
                                                'birth_country': 'USA',
                                                'birth_date': '1988-07-13T00:00:00',
                                                'birth_state': 'CA',
                                                'college': 'Louisiana State',
                                                'height_feet': '6',
                                                'height_inches': '4',
                                                'high_school': 'Brother Rice, '
                                                               'Bloomfield '
                                                               'Hills, MI',
                                                'league': 'AL',
                                                'name_display_first_last': 'DJ '
                                                                           'LeMahieu',
                                                'name_display_last_first': 'LeMahieu, '
                                                                           'DJ',
                                                'name_display_roster': 'LeMahieu',
                                                'name_first': 'DJ',
                                                'name_last': 'LeMahieu',
                                                'name_use': 'DJ',
                                                'player_id': '518934',
                                                'position': '2B',
                                                'position_id': '4',
                                                'pro_debut_date': '2011-05-30T00:00:00',
                                                'service_years': '',
                                                'sport_code': 'mlb',
                                                'team_abbrev': 'NYY',
                                                'team_code': 'nya',
                                                'team_full': 'New York Yankees',
                                                'team_id': '147',
                                                'throws': 'R',
                                                'weight': '215'},
                                        'totalSize': '1'}}}

In [6]:
#testing pulling specific data
data['search_player_all']['queryResults']['row']['bats']

'R'

In [7]:
#testing adding data from Json to list
nyy_df['Name'][0]
pInfoList = []
pInfoList.append(nyy_df['Name'][0])
pInfoList.append(data['search_player_all']['queryResults']['row']['bats'])
pInfoList

['DJ LeMahieu', 'R']

In [ ]:
#Adding specific data for each player to a list and adding each list to a list of lists
nyyInfo = []
i = 0
while i < len(nyy_df['Name']):
    pInfoList = []
    pInfoList.append(nyy_df['Name'][i])
    response = requests.get(url + "'"+nyy_df['Name'][i]+"'")
    data = response.json()
    try:
        pInfoList.append(data['search_player_all']['queryResults']['row']['bats'])
        pInfoList.append(data['search_player_all']['queryResults']['row']['throws'])
        pInfoList.append(data['search_player_all']['queryResults']['row']['position'])
    except:
        pInfoList.append('NaN')
        pInfoList.append('NaN')
        pInfoList.append('NaN')
    nyyInfo.append(pInfoList)
    i = i +1

In [ ]:
nyyInfo

In [ ]:
#converting list of lists to a dataframe
nyyJson = pd.DataFrame(nyyInfo)
nyyJson.columns=['Name', 'Bats', 'Throws', 'Position']
nyyJson.head()

In [ ]:
#connecting to SQL server (it is only slightly different for Postgres(see this week's activity 1), 
#I was never able to get postgres working so I use MySQL, think we c should turn in Postgres code though
#I created the etl database schema and tables in MySQL (see SQL file in repo)
#I was never able to get that server working)
rds_connection_string = "root:Babe1212@localhost:3306/etl"
engine = create_engine('postgresql://postgres:postgres@localhost:52398/databases')

In [ ]:
#use pandas to load CSV dataframe into database
nyy_df.to_sql(name='player_stats', con=engine, if_exists='append', index=False)

In [ ]:
#use pandas to load JSON dataframe into database
nyyJson.to_sql(name='player_Info', con=engine, if_exists='append', index=False)

In [ ]:
#confirm data has been added by querying
pd.read_sql_query('select * from player_stats', con=engine).head()

In [ ]:
#confirm data has been added by querying
pd.read_sql_query('select * from player_info', con=engine).head()